# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitident" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "b007db12fcdaf56801c57f10cee2bcd024aba6f690c8fa4c1acd9732cc17b21a"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "563ff6cf86ff58c3d0087fd1f72c3ca6e26959c87c8f99b0935595a276caf6fc"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d75d98e6c8297f3bdced915315b5c2d02af40c8d98c2b0e44e22db2d315d97d"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "487e89c4a4255eb89d224cecb88b78da794907c9b251bedd0c9ca2c3fa8085a7"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitident"
  desc "Keep git identities in one file and apply them per directory, remote or repo"
  homepage "https://github.com/leoru/gitident-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitident"
  binary "git-ident"
  bash_completion "completions/gitident.bash"
  fish_completion "completions/gitident.fish"
  zsh_completion "completions/_gitident"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitident"]
    end
  end

  # No zap stanza required
end
