# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitident" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "815e8ca218c51f7da22f4689d2b7b27e172b52c837c26bf452e309b6b7642c60"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "26b1bb5bc03880bde9017187ed55478aee5ed63e6619be489e54ed168a7f46fa"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0228ce8b6cf31b95841c30a8eec2fa06ed6402672a47d10a4802395bff33955c"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "333b54cbda7a92da4b657cf94043a51f04c21846fc5c1f8e22028dfc1af7d4c7"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitident"
  desc "Keep git identities in one file and apply them per directory, remote or repo"
  homepage "https://github.com/leoru/gitident-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitident"
  binary "git-ident"
  bash_completion "completions/gitident.bash"
  fish_completion "completions/gitident.fish"
  zsh_completion "completions/_gitident"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitident"]
    end
  end

  # No zap stanza required
end
