# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitident" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "9c6ea9e6b3f046c7e93e9528d956b54e2cbe82b60a1c49d3f5167ce9fa72d526"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ace9f8627c482fb455e2a8b62870d9111ede7fd925ae1c8bade9e14ad9de73d5"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f229220acfd22945512b523fb995d4eb0656eaaeb2be9316414b83ecb35fe952"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d400ea13fe554e1b4b1236bf294a48dd879f7fe77609676abd49b77639ea174f"
      url "https://github.com/leoru/gitident-cli/releases/download/v#{version}/gitident_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitident"
  desc "Keep git identities in one file and apply them per directory, remote or repo"
  homepage "https://github.com/leoru/gitident-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitident"
  binary "git-ident"
  bash_completion "completions/gitident.bash"
  fish_completion "completions/gitident.fish"
  zsh_completion "completions/_gitident"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitident"]
    end
  end

  # No zap stanza required
end
